// Data Memory Interface
// Bridges MEM stage to external data memory.
// Passes byte-enable and word-aligned address generated by mem_stage.
module data_mem_if #(
    parameter XLEN        = 32,
    parameter DMEM_DWIDTH = 32
) (
    // From MEM stage
    input  logic                   req_i,
    input  logic                   we_i,
    input  logic [3:0]             be_i,
    input  logic [XLEN-1:0]        addr_i,
    input  logic [DMEM_DWIDTH-1:0] wdata_i,

    // To external data memory
    output logic                   dmem_req_o,
    output logic                   dmem_we_o,
    output logic [3:0]             dmem_be_o,
    output logic [XLEN-1:0]        dmem_addr_o,
    output logic [DMEM_DWIDTH-1:0] dmem_wdata_o,

    // From external data memory
    input  logic [DMEM_DWIDTH-1:0] dmem_rdata_i,
    input  logic                   dmem_ready_i,

    // To MEM stage
    output logic [DMEM_DWIDTH-1:0] rdata_o,
    output logic                   ready_o
);

    always_comb begin
        dmem_req_o   = req_i;
        dmem_we_o    = we_i;
        dmem_be_o    = be_i;
        dmem_addr_o  = {addr_i[XLEN-1:2], 2'b00}; // word-aligned
        dmem_wdata_o = wdata_i;
        rdata_o      = dmem_rdata_i;
        ready_o      = dmem_ready_i;
    end

endmodule
